version: "3"
services:
  chatbot:
    build: 
      context: .
      dockerfile: Dockerfile
    image: chatbot
    container_name: chatbot
    restart: always
    # ports:
    #   - "5000:5000"
    env_file: .env
    # volumes:
    #   - ./chatbot:/app
