version: "3"
services:
  chatbot:
    build: 
      context: .
      dockerfile: Dockerfile
    image: chatgrambot
    container_name: chatgrambot
    restart: always
    # ports:
    #   - "5000:5000"
    env_file: .env
    volumes:
      # - ./chatbot:/app
      - ./db:/app/db
